//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarDatalogger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolarData
    {
        public int Id { get; set; }
        public Nullable<int> TimeInserted { get; set; }
        public Nullable<double> VoltageOne { get; set; }
        public Nullable<double> VoltageTwo { get; set; }
        public Nullable<double> VoltageThree { get; set; }
        public Nullable<double> Temperature { get; set; }
    }
}
